# Generated by Django 5.2.4 on 2025-07-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(db_index=True, help_text='Name of the plant', max_length=100, unique=True)),
                ('scheduled_lprs', models.TimeField(help_text='Scheduled LPRS time (HH:MM:SS)', verbose_name='Scheduled LPRS')),
                ('scheduled_print_start', models.TimeField(help_text='Scheduled print start time (HH:MM:SS)', verbose_name='Scheduled Print Start')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Scheduled Time',
                'verbose_name_plural': 'Scheduled Times',
                'db_table': 'scheduled_time',
                'ordering': ['plant_name'],
                'indexes': [models.Index(fields=['plant_name', 'is_active'], name='scheduled_t_plant_n_a3b1a7_idx')],
            },
        ),
    ]
