# Generated by Django 5.2.4 on 2025-07-31 11:01

from django.db import migrations


def populate_scheduled_times(apps, schema_editor):
    ScheduledTime = apps.get_model('handler_default_data', 'ScheduledTime')

    scheduled_times_data = [
        {'plant_name': 'Vejalpur', 'scheduled_lprs': '00:00:00', 'scheduled_print_start': '00:30:00'},
        {'plant_name': 'Airoli', 'scheduled_lprs': '00:00:00', 'scheduled_print_start': '00:30:00'},
        {'plant_name': 'Baroda', 'scheduled_lprs': '00:15:00', 'scheduled_print_start': '00:45:00'},
        {'plant_name': 'Bommasandra', 'scheduled_lprs': '00:00:00', 'scheduled_print_start': '00:30:00'},
        {'plant_name': 'Chemmencherry', 'scheduled_lprs': '00:00:00', 'scheduled_print_start': '00:30:00'},
        {'plant_name': 'Nacharam', 'scheduled_lprs': '00:00:00', 'scheduled_print_start': '00:30:00'},
        {'plant_name': 'Kandivali', 'scheduled_lprs': '00:00:00', 'scheduled_print_start': '00:30:00'},
        {'plant_name': 'Saltlake', 'scheduled_lprs': '00:00:00', 'scheduled_print_start': '00:30:00'},
        {'plant_name': 'Chinhat', 'scheduled_lprs': '01:05:00', 'scheduled_print_start': '01:35:00'},
        {'plant_name': 'Manesar', 'scheduled_lprs': '00:30:00', 'scheduled_print_start': '00:30:00'},
        {'plant_name': 'Butibori', 'scheduled_lprs': '01:00:00', 'scheduled_print_start': '01:30:00'},
        {'plant_name': 'Bhosari', 'scheduled_lprs': '00:30:00', 'scheduled_print_start': '01:00:00'},
        {'plant_name': 'Sahibabad', 'scheduled_lprs': '00:00:00', 'scheduled_print_start': '00:30:00'},
        {'plant_name': 'Trivandrum', 'scheduled_lprs': '00:00:00', 'scheduled_print_start': '00:30:00'},
    ]

    for data in scheduled_times_data:
        ScheduledTime.objects.create(**data)


def reverse_populate_scheduled_times(apps, schema_editor):
    ScheduledTime = apps.get_model('handler_default_data', 'ScheduledTime')
    ScheduledTime.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('handler_default_data', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_scheduled_times, reverse_populate_scheduled_times),
    ]
