# Generated by Django 5.2.4 on 2025-08-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler_default_data', '0002_populate_scheduled_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtime',
            name='scheduled_print_finish',
            field=models.TimeField(blank=True, help_text='Scheduled print finish time (HH:MM:SS)', null=True, verbose_name='Scheduled Print Finish'),
        ),
    ]
