# Generated by Django 5.2.4 on 2025-09-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler_default_data', '0005_populate_print_finish_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtime',
            name='planned_folders',
            field=models.IntegerField(default=1, help_text='Number of planned folders for this plant', verbose_name='Planned Folders'),
        ),
    ]
