# Generated by Django 5.2.4 on 2025-10-06 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.CharField(help_text='Plant ID from plant_details (e.g., ODBCAIR30)', max_length=20)),
                ('plant_name', models.CharField(help_text='Display name (e.g., Airoli)', max_length=100)),
                ('issue_date', models.DateField(help_text='Issue date for the report')),
                ('remarks_toi', models.TextField(blank=True, help_text='Remarks for TOI publications', null=True)),
                ('remarks_others', models.TextField(blank=True, help_text='Remarks for other publications', null=True)),
                ('first_time_execution_info', models.TextField(blank=True, help_text='First-time execution details', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagination_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pagination Report',
                'verbose_name_plural': 'Pagination Reports',
                'db_table': 'pagination_report',
                'ordering': ['-issue_date', 'plant_name'],
            },
        ),
        migrations.CreateModel(
            name='GNPInformation',
            fields=[
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='gnp_info', serialize=False, to='pagination_dash.paginationreport')),
                ('et', models.BooleanField(default=False, verbose_name='Economic Times')),
                ('mt', models.BooleanField(default=False, verbose_name='Maharashtra Times')),
                ('mirror', models.BooleanField(default=False, verbose_name='Mirror')),
                ('nbt', models.BooleanField(default=False, verbose_name='Navbharat Times')),
                ('remarks', models.TextField(blank=True, help_text='GNP-specific remarks', null=True)),
            ],
            options={
                'verbose_name': 'GNP Information',
                'verbose_name_plural': 'GNP Information',
                'db_table': 'gnp_information',
            },
        ),
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(choices=[('TOI B-1', 'TOI B-1'), ('TOI B-2', 'TOI B-2'), ('BT B-1', 'BT B-1'), ('BT B-2', 'BT B-2'), ('TOI Supp-1', 'TOI Supp-1'), ('TOI Supp-2', 'TOI Supp-2'), ('TOI Supp-3', 'TOI Supp-3')], max_length=50)),
                ('snp_pages', models.PositiveIntegerField(default=0, help_text='Standard News Pages')),
                ('gnp_pages_type', models.CharField(blank=True, choices=[('2 Pg Jkt', '2 Pg Jkt'), ('4 Pg Jkt - 2 diff clients', '4 Pg Jkt - 2 diff clients'), ('4 Pg Vantage', '4 Pg Vantage'), ('4 Pg Power Jkt', '4 Pg Power Jkt'), ('8 Pg Super-pano', '8 Pg Super-pano'), ('6 Pg GNP', '6 Pg GNP'), ('8 Pg GNP', '8 Pg GNP')], max_length=50, null=True, verbose_name='GNP Pages Type')),
                ('gnp_pages_count', models.PositiveIntegerField(default=0, help_text='Auto-populated based on GNP type')),
                ('total_pages', models.PositiveIntegerField(default=0, help_text='SNP Pages + GNP Pages Count')),
                ('number_of_gnp_jackets', models.PositiveIntegerField(default=0, verbose_name='Number of GNP Jackets')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='pagination_dash.paginationreport')),
            ],
            options={
                'verbose_name': 'Book Details',
                'verbose_name_plural': 'Book Details',
                'db_table': 'book_details',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='paginationreport',
            index=models.Index(fields=['plant_id', 'issue_date'], name='pagination__plant_i_0f90a5_idx'),
        ),
        migrations.AddIndex(
            model_name='paginationreport',
            index=models.Index(fields=['issue_date'], name='pagination__issue_d_770e52_idx'),
        ),
        migrations.AddIndex(
            model_name='paginationreport',
            index=models.Index(fields=['plant_id'], name='pagination__plant_i_56fc11_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paginationreport',
            unique_together={('plant_id', 'issue_date')},
        ),
        migrations.AddIndex(
            model_name='bookdetails',
            index=models.Index(fields=['report', 'book_name'], name='book_detail_report__189879_idx'),
        ),
        migrations.AddIndex(
            model_name='bookdetails',
            index=models.Index(fields=['order'], name='book_detail_order_4c143a_idx'),
        ),
    ]
