# Generated by Django 5.2.4 on 2025-10-07 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagination_dash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor_name', models.CharField(help_text='Competitor newspaper name', max_length=100)),
                ('snp_pages', models.PositiveIntegerField(default=0, help_text='Standard News Pages', verbose_name='SNP Pages')),
                ('gnp_pages', models.PositiveIntegerField(default=0, help_text='Good News Pages', verbose_name='GNP Pages')),
                ('total_pages', models.PositiveIntegerField(default=0, help_text='Auto-calculated: SNP + GNP Pages')),
                ('gnp_jkts_main', models.PositiveIntegerField(default=0, help_text='Number of GNP Jackets in Main', verbose_name='GNP Jackets in Main')),
                ('gnp_jkts_supplement', models.PositiveIntegerField(default=0, help_text='Number of GNP Jackets in Supplement', verbose_name='GNP Jackets in Supplement')),
                ('total_gnp_jkts', models.PositiveIntegerField(default=0, help_text='Auto-calculated: GNP Jackets Main + Supplement', verbose_name='Total GNP Jackets')),
                ('comment', models.TextField(blank=True, help_text='Additional comments about competitor', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='pagination_dash.paginationreport')),
            ],
            options={
                'verbose_name': 'Competitor Data',
                'verbose_name_plural': 'Competitor Data',
                'db_table': 'competitor_data',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['report', 'competitor_name'], name='competitor__report__cdce9b_idx'), models.Index(fields=['order'], name='competitor__order_4d97fd_idx')],
            },
        ),
    ]
