# Generated by Django 5.2.4 on 2025-10-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagination_dash', '0002_competitordata'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitordata',
            name='innovation',
            field=models.JSONField(blank=True, default=list, help_text='Multiple innovation types (stored as JSON array)', null=True, verbose_name='Innovation'),
        ),
    ]
