# Generated by Django 5.2.4 on 2025-10-09 08:16

import django.db.models.deletion
from django.db import migrations, models


def migrate_competitor_data_forward(apps, schema_editor):
    """
    Migrate existing competitor data to new CompetitorBookDetails structure.
    For each CompetitorData:
    - Create 2 CompetitorBookDetails entries (Main and Supplement)
    - Split snp_pages equally between Main and Supplement
    - Split gnp_pages equally between Main and Supplement
    """
    CompetitorData = apps.get_model('pagination_dash', 'CompetitorData')
    CompetitorBookDetails = apps.get_model('pagination_dash', 'CompetitorBookDetails')

    for competitor in CompetitorData.objects.all():
        # Get existing data
        snp_pages = getattr(competitor, 'snp_pages', 0) or 0
        gnp_pages = getattr(competitor, 'gnp_pages', 0) or 0
        total_pages = getattr(competitor, 'total_pages', 0) or 0

        # Split pages between Main and Supplement
        # Main gets the larger portion if odd numbers
        main_snp = (snp_pages + 1) // 2
        supp_snp = snp_pages // 2

        main_gnp = (gnp_pages + 1) // 2
        supp_gnp = gnp_pages // 2

        # Create Main book details
        CompetitorBookDetails.objects.create(
            competitor=competitor,
            book_type='Main',
            snp_pages=main_snp,
            gnp_pages_type=None,  # Can't determine type from count alone
            gnp_pages_count=main_gnp,
            total_pages=main_snp + main_gnp
        )

        # Create Supplement book details
        CompetitorBookDetails.objects.create(
            competitor=competitor,
            book_type='Supplement',
            snp_pages=supp_snp,
            gnp_pages_type=None,
            gnp_pages_count=supp_gnp,
            total_pages=supp_snp + supp_gnp
        )


def migrate_competitor_data_reverse(apps, schema_editor):
    """
    Reverse migration: aggregate CompetitorBookDetails back to CompetitorData
    """
    CompetitorData = apps.get_model('pagination_dash', 'CompetitorData')
    CompetitorBookDetails = apps.get_model('pagination_dash', 'CompetitorBookDetails')

    for competitor in CompetitorData.objects.all():
        books = CompetitorBookDetails.objects.filter(competitor=competitor)

        total_snp = sum(book.snp_pages for book in books)
        total_gnp = sum(book.gnp_pages_count for book in books)

        competitor.snp_pages = total_snp
        competitor.gnp_pages = total_gnp
        competitor.total_pages = total_snp + total_gnp
        competitor.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pagination_dash', '0004_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorBookDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_type', models.CharField(choices=[('Main', 'Main'), ('Supplement', 'Supplement')], help_text='Book type: Main or Supplement', max_length=20)),
                ('snp_pages', models.PositiveIntegerField(default=0, help_text='Standard News Pages', verbose_name='SNP Pages')),
                ('gnp_pages_type', models.CharField(blank=True, choices=[('2 Pg Jkt', '2 Pg Jkt'), ('4 Pg Jkt - 2 diff clients', '4 Pg Jkt - 2 diff clients'), ('4 Pg Vantage', '4 Pg Vantage'), ('4 Pg Power Jkt', '4 Pg Power Jkt'), ('8 Pg Super-pano', '8 Pg Super-pano'), ('6 Pg GNP', '6 Pg GNP'), ('8 Pg GNP', '8 Pg GNP')], max_length=50, null=True, verbose_name='GNP Pages Type')),
                ('gnp_pages_count', models.PositiveIntegerField(default=0, help_text='Auto-populated based on GNP type')),
                ('total_pages', models.PositiveIntegerField(default=0, help_text='SNP Pages + GNP Pages Count')),
            ],
            options={
                'verbose_name': 'Competitor Book Details',
                'verbose_name_plural': 'Competitor Book Details',
                'db_table': 'competitor_book_details',
                'ordering': ['book_type'],
            },
        ),
        migrations.AddField(
            model_name='competitorbookdetails',
            name='competitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_details', to='pagination_dash.competitordata'),
        ),
        migrations.AddIndex(
            model_name='competitorbookdetails',
            index=models.Index(fields=['competitor', 'book_type'], name='competitor__competi_05f7bd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='competitorbookdetails',
            unique_together={('competitor', 'book_type')},
        ),
        # Migrate data from old structure to new
        migrations.RunPython(migrate_competitor_data_forward, migrate_competitor_data_reverse),
        # Now remove old fields
        migrations.AlterModelOptions(
            name='competitordata',
            options={'ordering': ['id'], 'verbose_name': 'Competitor Data', 'verbose_name_plural': 'Competitor Data'},
        ),
        migrations.RemoveIndex(
            model_name='competitordata',
            name='competitor__order_4d97fd_idx',
        ),
        migrations.RemoveField(
            model_name='competitordata',
            name='gnp_jkts_main',
        ),
        migrations.RemoveField(
            model_name='competitordata',
            name='gnp_jkts_supplement',
        ),
        migrations.RemoveField(
            model_name='competitordata',
            name='gnp_pages',
        ),
        migrations.RemoveField(
            model_name='competitordata',
            name='order',
        ),
        migrations.RemoveField(
            model_name='competitordata',
            name='snp_pages',
        ),
        migrations.RemoveField(
            model_name='competitordata',
            name='total_gnp_jkts',
        ),
        migrations.RemoveField(
            model_name='competitordata',
            name='total_pages',
        ),
        migrations.AlterField(
            model_name='bookdetails',
            name='book_name',
            field=models.CharField(choices=[('TOI B-1', 'TOI B-1'), ('TOI B-2', 'TOI B-2'), ('TIMS B-1', 'TIMS B-1'), ('TIMS B-2', 'TIMS B-2'), ('TOI Supp-1', 'TOI Supp-1'), ('TOI Supp-2', 'TOI Supp-2'), ('TOI Supp-3', 'TOI Supp-3')], max_length=50),
        ),
    ]
