# Generated by Django 5.2.4 on 2025-10-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagination_dash', '0005_competitorbookdetails_alter_competitordata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gnpinformation',
            name='tims',
            field=models.BooleanField(default=False, verbose_name='TIMS'),
        ),
    ]
