# Generated by Django 5.2.4 on 2025-10-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagination_dash', '0006_gnpinformation_tims'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitorbookdetails',
            name='number_of_books',
            field=models.PositiveIntegerField(default=0, help_text='Total number of books for competitor', verbose_name='Number of Books'),
        ),
        migrations.AddField(
            model_name='competitorbookdetails',
            name='number_of_gnp_jacket',
            field=models.PositiveIntegerField(default=0, help_text='Number of GNP jackets for competitor', verbose_name='Number of GNP Jacket'),
        ),
    ]
