# Generated by Django 5.2.4 on 2025-11-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagination_dash', '0007_competitorbookdetails_number_of_books_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdetails',
            name='balloon_printed',
            field=models.BooleanField(default=False, help_text='Indicates if balloon was printed (only for TOI B-2 or TIMS B-2)', verbose_name='Balloon Printed'),
        ),
        migrations.AddField(
            model_name='bookdetails',
            name='has_masthead',
            field=models.BooleanField(default=False, help_text='Indicates if masthead is present (only for TOI B-2 or TIMS B-2)', verbose_name='Has Masthead'),
        ),
    ]
