# Generated by Django 5.2.4 on 2025-11-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagination_dash', '0008_bookdetails_balloon_printed_bookdetails_has_masthead'),
    ]

    operations = [
        migrations.AddField(
            model_name='gnpinformation',
            name='et_had_2_books',
            field=models.BooleanField(default=False, help_text='Indicates if Economic Times publication had 2 books', verbose_name='ET had 2 Books'),
        ),
    ]
