# Generated by Django 5.2.4 on 2025-11-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagination_dash', '0009_gnpinformation_et_had_2_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='gnpinformation',
            name='et_b1',
            field=models.BooleanField(default=False, help_text='ET Book 1 had GNP', verbose_name='ET B-1'),
        ),
        migrations.AddField(
            model_name='gnpinformation',
            name='et_b2',
            field=models.BooleanField(default=False, help_text='ET Book 2 had GNP', verbose_name='ET B-2'),
        ),
    ]
