# Generated by Django 5.2.4 on 2025-07-23 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionReport',
            fields=[
                ('issueid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('issue_date', models.DateField(db_index=True)),
                ('runid', models.CharField(max_length=20)),
                ('edition', models.CharField(max_length=100)),
                ('products', models.CharField(db_index=True, max_length=200)),
                ('main_supplement', models.CharField(max_length=20)),
                ('no_of_books', models.IntegerField()),
                ('machine', models.CharField(max_length=20)),
                ('folder', models.CharField(db_index=True, max_length=20)),
                ('print_order', models.IntegerField()),
                ('gross_counter', models.IntegerField()),
                ('waste', models.IntegerField()),
                ('waste_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('production_start', models.DateTimeField()),
                ('production_end', models.DateTimeField()),
                ('production_start_date', models.DateField()),
                ('production_end_date', models.DateField()),
                ('total_run_time_mnts', models.IntegerField()),
                ('total_downtime', models.IntegerField()),
                ('number_of_stoppages', models.IntegerField()),
                ('wb_s', models.IntegerField()),
                ('avg_speed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_pages', models.CharField(max_length=30)),
                ('sum_of_pages', models.IntegerField()),
                ('color_pages', models.CharField(max_length=30, null=True)),
                ('bw_pages', models.CharField(max_length=20, null=True)),
                ('broad_sheets', models.CharField(max_length=50, null=True)),
                ('tabloid', models.CharField(max_length=30, null=True)),
                ('user_name', models.CharField(max_length=50, null=True)),
                ('in_charge', models.CharField(max_length=50, null=True)),
                ('machine_in_charge', models.CharField(max_length=50, null=True)),
                ('officers', models.CharField(max_length=100, null=True)),
                ('remarks', models.TextField(null=True)),
                ('accidents', models.TextField(null=True)),
                ('print_finish_delay_reason', models.TextField(null=True)),
                ('entry_time', models.DateTimeField()),
                ('plant_name', models.CharField(max_length=50)),
                ('complexity', models.CharField(max_length=3)),
                ('complexities', models.CharField(max_length=10)),
                ('production_type', models.CharField(max_length=20)),
                ('reason_for_additional_folder', models.CharField(max_length=50, null=True)),
                ('uv', models.CharField(max_length=3)),
                ('last_truck', models.CharField(max_length=10, null=True)),
                ('last_bundle', models.CharField(max_length=10, null=True)),
                ('towers_used', models.CharField(max_length=100, null=True)),
                ('towers_count', models.IntegerField(null=True)),
                ('run_date', models.DateField()),
                ('status', models.CharField(max_length=1, null=True)),
                ('folders_count', models.IntegerField(choices=[(1, '1'), (2, '2')])),
                ('uv_run', models.BooleanField()),
            ],
            options={
                'db_table': 'production_report',
                'indexes': [models.Index(fields=['issue_date'], name='production__issue_d_906592_idx'), models.Index(fields=['folder'], name='production__folder_7c7f86_idx'), models.Index(fields=['products'], name='production__product_9afb07_idx'), models.Index(fields=['folders_count'], name='production__folders_437e13_idx'), models.Index(fields=['uv_run'], name='production__uv_run_21dd35_idx')],
            },
        ),
        migrations.CreateModel(
            name='Innovation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookid', models.CharField(max_length=24)),
                ('issue_date', models.DateField()),
                ('runid', models.IntegerField(null=True)),
                ('product_name', models.CharField(max_length=200)),
                ('desk', models.CharField(max_length=100)),
                ('edition', models.CharField(max_length=100)),
                ('machine', models.CharField(max_length=50)),
                ('folder', models.CharField(max_length=50)),
                ('innovation', models.CharField(max_length=100)),
                ('impact', models.DecimalField(decimal_places=2, max_digits=10)),
                ('complexity', models.BooleanField(null=True)),
                ('complexities', models.CharField(max_length=100, null=True)),
                ('plant_name', models.CharField(max_length=100)),
                ('production_type', models.CharField(max_length=5, null=True)),
                ('uv', models.BooleanField(default=False, null=True)),
                ('reflong', models.BooleanField(default=False, null=True)),
                ('issueid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innovations', to='upload_from_pi.productionreport')),
            ],
            options={
                'db_table': 'innovations',
                'indexes': [models.Index(fields=['bookid'], name='innovations_bookid_23162b_idx'), models.Index(fields=['issue_date'], name='innovations_issue_d_b0d2aa_idx'), models.Index(fields=['runid'], name='innovations_runid_d43b75_idx')],
            },
        ),
    ]
