# Generated by Django 5.2.4 on 2025-07-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_from_pi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downtime',
            name='action_taken',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='downtime',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='downtime',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
