# Generated by Django 5.2.4 on 2025-07-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_from_pi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionreport',
            name='final_score',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productionreport',
            name='innovation_rank',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='productionreport',
            name='predicted_runtime',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productionreport',
            name='runtime_score',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productionreport',
            name='runtime_variance',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productionreport',
            name='waste_score',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productionreport',
            name='waste_variance',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
