# Generated by Django 5.2.4 on 2025-07-28 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_from_pi', '0002_alter_downtime_action_taken_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReelConsumption',
            fields=[
                ('reel_consumption_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('edition_date', models.DateField()),
                ('runid', models.CharField(max_length=50)),
                ('edition', models.CharField(max_length=200)),
                ('sapid', models.CharField(max_length=50)),
                ('captured_consumption', models.IntegerField()),
                ('actual_consumption', models.IntegerField()),
                ('sap_weight', models.IntegerField()),
                ('machine', models.CharField(max_length=50)),
                ('reelstand', models.CharField(max_length=50)),
                ('material_code', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=100)),
                ('gsm', models.IntegerField()),
                ('color', models.CharField(max_length=10)),
                ('paper_type', models.CharField(max_length=50)),
                ('no_of_wb', models.IntegerField()),
                ('operator', models.CharField(max_length=100)),
                ('plant', models.CharField(max_length=100)),
                ('production_type_folder', models.CharField(max_length=10)),
                ('folder', models.CharField(max_length=50)),
                ('manufacture_code', models.CharField(blank=True, max_length=100, null=True)),
                ('defect_code', models.CharField(blank=True, max_length=100, null=True)),
                ('product_name', models.CharField(max_length=200)),
                ('np_size_code', models.CharField(max_length=10)),
                ('np_width_in_pgs', models.IntegerField()),
                ('print_order', models.IntegerField()),
                ('production_type_factor', models.IntegerField()),
                ('issueid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reel_consumptions', to='upload_from_pi.productionreport')),
            ],
            options={
                'db_table': 'reel_consumption',
                'indexes': [models.Index(fields=['edition_date', 'runid'], name='reel_consum_edition_cf7816_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebBreak',
            fields=[
                ('web_break_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('edition_date', models.DateField()),
                ('runid', models.CharField(max_length=50)),
                ('edition', models.CharField(max_length=200)),
                ('machine', models.CharField(max_length=50)),
                ('folder', models.CharField(max_length=50)),
                ('sapid', models.CharField(max_length=50)),
                ('reelstand', models.CharField(max_length=50)),
                ('arm', models.CharField(max_length=50)),
                ('material_code', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=100)),
                ('gsm', models.IntegerField()),
                ('color', models.CharField(max_length=10)),
                ('paper_type', models.CharField(max_length=50)),
                ('operator', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('plant_name', models.CharField(max_length=100)),
                ('products', models.CharField(max_length=200)),
                ('main_supplement', models.CharField(max_length=50)),
                ('no_of_books', models.IntegerField()),
                ('complexity', models.CharField(max_length=10)),
                ('complexities', models.TextField()),
                ('production_type', models.CharField(max_length=10)),
                ('uv', models.CharField(max_length=10)),
                ('run_date', models.DateField()),
                ('manufacture_code', models.CharField(blank=True, max_length=100, null=True)),
                ('defect_code', models.CharField(blank=True, max_length=100, null=True)),
                ('issueid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_breaks', to='upload_from_pi.productionreport')),
            ],
            options={
                'db_table': 'web_break',
                'indexes': [models.Index(fields=['edition_date', 'runid'], name='web_break_edition_119403_idx')],
            },
        ),
    ]
