# Generated by Django 5.2.4 on 2025-07-29 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_from_pi', '0003_reelconsumption_webbreak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reelconsumption',
            name='color',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reelconsumption',
            name='folder',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reelconsumption',
            name='gsm',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reelconsumption',
            name='machine',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reelconsumption',
            name='manufacturer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reelconsumption',
            name='material',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reelconsumption',
            name='material_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reelconsumption',
            name='no_of_wb',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reelconsumption',
            name='np_size_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reelconsumption',
            name='np_width_in_pgs',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reelconsumption',
            name='operator',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reelconsumption',
            name='paper_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reelconsumption',
            name='plant',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reelconsumption',
            name='print_order',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reelconsumption',
            name='product_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reelconsumption',
            name='production_type_factor',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reelconsumption',
            name='production_type_folder',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reelconsumption',
            name='reelstand',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='webbreak',
            name='arm',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='webbreak',
            name='color',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='webbreak',
            name='complexities',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='webbreak',
            name='complexity',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='webbreak',
            name='gsm',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='webbreak',
            name='main_supplement',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='webbreak',
            name='manufacturer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='webbreak',
            name='material',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='webbreak',
            name='material_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='webbreak',
            name='no_of_books',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='webbreak',
            name='operator',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='webbreak',
            name='paper_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='webbreak',
            name='production_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='webbreak',
            name='products',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='webbreak',
            name='reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='webbreak',
            name='reelstand',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
