# Generated by Django 5.2.4 on 2025-07-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_from_pi', '0004_alter_reelconsumption_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downtime',
            name='runid',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='downtime',
            name='scheduled',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
