# Generated by Django 5.2.4 on 2025-07-29 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_from_pi', '0005_alter_downtime_runid_alter_downtime_scheduled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookwisedetails',
            name='runid',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='runid',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reelconsumption',
            name='runid',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='webbreak',
            name='runid',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
