# Generated by Django 5.2.4 on 2025-07-29 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_from_pi', '0006_alter_bookwisedetails_runid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookwisedetails',
            name='avg_speed',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bookwisedetails',
            name='baloon_folder',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bookwisedetails',
            name='book_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bookwisedetails',
            name='change_over_time_mins',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bookwisedetails',
            name='change_over_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookwisedetails',
            name='ctp_product',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bookwisedetails',
            name='editorial_release',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='bookwisedetails',
            name='first_tiff',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='bookwisedetails',
            name='last_plate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='bookwisedetails',
            name='last_tiff',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='bookwisedetails',
            name='no_of_stoppages',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bookwisedetails',
            name='plate_issued',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bookwisedetails',
            name='production_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bookwisedetails',
            name='reflong',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bookwisedetails',
            name='replates',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bookwisedetails',
            name='startup_waste',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bookwisedetails',
            name='total_downtime',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bookwisedetails',
            name='total_run_time_mnts',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bookwisedetails',
            name='w_bs',
            field=models.IntegerField(null=True),
        ),
    ]
