# Generated by Django 5.2.4 on 2025-07-30 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_from_pi', '0007_alter_bookwisedetails_avg_speed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionreport',
            name='toi_city',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='runid',
            field=models.CharField(default=False, max_length=20),
            preserve_default=False,
        ),
    ]
