# Generated by Django 5.2.4 on 2025-08-01 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_from_pi', '0008_productionreport_toi_city_and_more'),
    ]

    operations = [
    ]
