# Generated by Django 5.2.4 on 2025-08-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_from_pi', '0009_populate_print_finish_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downtime',
            name='complexities',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='downtime',
            name='complexity',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='downtime',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='downtime',
            name='reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='downtime',
            name='related',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
