# Generated by Django 5.2.4 on 2025-08-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_from_pi', '0010_alter_downtime_complexities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reelconsumption',
            name='product_name',
            field=models.TextField(null=True),
        ),
    ]
