# Generated by Django 5.2.4 on 2025-08-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_from_pi', '0011_alter_reelconsumption_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionreport',
            name='in_charge',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='machine_in_charge',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='officers',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='user_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
