# Generated by Django 5.2.4 on 2025-10-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_from_pi', '0012_alter_productionreport_in_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookwisedetails',
            name='waste_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
